apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router
  namespace: myic02
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: mysql-router
  template:
    metadata:
      labels:
        app: mysql-router
        version: v1
    spec:
      containers:
      - name: mysql-router
        image: mysql/mysql-router
        env:
        - name: MYSQL_HOST
          value: "mycluster"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "sakila"
        - name: MYSQL_ROUTER_BOOTSTRAP_EXTRA_OPTIONS
          value: "--conf-set-option=routing:bootstrap_rw.max_connect_errors=500 --conf-set-option=routing:bootstrap_ro.max_connect_errors=500"
        imagePullPolicy: Always
        ports:
        - containerPort: 6446
